services:
  app:
    build:
      context: .
    container_name: laravel_app
    depends_on:
      - db
      - redis

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro # <-- CHANGED THIS LINE
    depends_on:
      - app
    environment:
      - SERVER_NAME=${SERVER_NAME}

  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # KEEP THIS! Essential for database persistence

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379" #EEP THIS - Redis is fine without a volume if used only for temporary cache

  queue:
    build: .
    container_name: queue_worker
    command: php artisan queue:work
    restart: unless-stopped
    depends_on:
      - db
      - redis

  scheduler:
    build: .
    container_name: scheduler
    command: php artisan schedule:work
    depends_on:
      - db
      - redis

volumes:
  pgdata:
